#!/bin/bash

#/
#--------------------------------------------------------------------------
# Install Larasail
#--------------------------------------------------------------------------
#
# This part of the script will move a few files to the necessary locations,
# add a new user 'sail', and add aliases for the CLI
#
#/


# Move the files to /etc/.sail and create a root sail alias
mv larasail-master/.sail /etc/.sail
echo "alias sail='sh /etc/.sail/sail'" >> /etc/bash.bashrc


# Create a new password and create our new sail user
PASS=$(openssl rand -base64 32)
useradd -G sudo -d /home/sail -p $PASS -m sail -s /bin/bash


# Give the sail user ability to not always require password
echo 'sail ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers


# Turn on SSH Passwords
# sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
# echo -n 'AllowUsers sail' >> /etc/ssh/sshd_config
# service ssh reload


# Store the sail user password
if [ ! -d /etc/.sail/tmp ]; then
  sudo mkdir /etc/.sail/tmp
fi
sudo echo $PASS > /etc/.sail/tmp/pass

sudo chown -R sail:sail /etc/.sail/tmp


# Include our colors and format scripts
. /etc/.sail/includes/colors
. /etc/.sail/includes/format


# Add sail alias to sail bashrc and the bin path dir for composer
echo "alias sail='sh /etc/.sail/sail'" >> /home/sail/.bashrc
echo "export PATH=~/.config/composer/vendor/bin:~/.composer/vendor/bin:\$PATH" >> /home/sail/.bashrc


# Show message after successfully installing
setsailNoColor
barNoColor
echo "| Prepare the Sails, we're ready for the Open Sea!";
barNoColor


# Remove sail folder pulled from git repo and switch user to sail
rm -rf larasail-master
su - sail
