#!/bin/bash

#/
#--------------------------------------------------------------------------
# Larasail Environment Launcher
#--------------------------------------------------------------------------
#
# Enter shell as sail user
#
#/

if [ "$(whoami)" != "sail" ]; then
    sudo su - sail
else
    echo "Already logged in as sail"
fi
