#!/bin/bash

#/
#--------------------------------------------------------------------------
# Larasail User Password
#--------------------------------------------------------------------------
#
# This file will display the Larasail user password
#
#/

. /etc/.sail/includes/colors
. /etc/.sail/includes/format

setsail

PASS=$(cat /etc/.sail/tmp/pass)

bar
cyan "| LaraSail User Password:"
cyan "| $PASS"
bar
