#!/bin/bash

#/
#--------------------------------------------------------------------------
# Larasail Main File
#--------------------------------------------------------------------------
#
# This file will pass the argument to the necessary script.
#
#/

if [ "$1" = "-h" ] || [ -z $1 ]
then
    . /etc/.sail/includes/help
elif [ "$1" = "host" ] ; then
	sudo sh /etc/.sail/$1 $2 $3
else
    . /etc/.sail/$1 $2 $3
fi
